### ISSUE TITLE
Hardcoded busybox image

### ISSUE THREAD

**Issue by OmegaVVeapon** [datawire/ambassador-chart#121]
Hi,

When checking out the latest chart, I noticed that the `Pod` that gets created in [test-ready](https://github.com/datawire/ambassador-chart/blob/master/templates/tests/test-ready.yaml) uses a `busybox` image.

While this would normally be fine, many companies have very strict security measures in place that prevent pulling images from non-internal registries (like DockerHub in this case).

Would you be open to me submitting a PR make it possible to set the path from which to get this busybox image in the values.yaml?

Maybe something under a `test` field like:

```
test:
  image: my-company.com/busybox:1.0.0
```

**Comment by djsly** [comment]
@alexgervais  are you ok for getting a PR ? 

also could me make it togglelable

**Comment by alexgervais** [comment]
@djsly a PR would be great!
@inercia can assist in reviewing and providing feedback :)
