### ISSUE TITLE
installing chart 2.1.0 (old!)

### ISSUE THREAD

**Issue by schollii** [datawire/ambassador-chart#148]
Hi, we have been using 2.1.0 for a while and are not ready to upgrade yet, but with the recent deprecation of charts.helm.sh we no longer have access to https://charts.helm.sh/stable/ambassador-2.1.0.tgz, and I'm not seeing that release tagged in your github repo. Some possibilities: 

- Is there a way of getting 2.1.0 chart from your repo?  
- I found a copy at https://helm.jamko.ir/ambassador-2.1.0.tgz, but that one does not seem to be a helm repo
- I found another copy at https://kubernetes-charts.storage.googleapis.com/ambassador-2.1.0.tgz, that one seems to be in a repo, but it seems deprecated too, although `helm repo add stable https://kubernetes-charts.storage.googleapis.com --allow-deprecated-repos` seems to work but for how long? Without the flag, helm repo add recommends using charts.helm.sh but that one no longer hosts ambassador 2.1.0
- I could attempt to upgrade ambassador to latest but not sure if anything would break

**Comment by josuevalverde12** [comment]
Artifactory's chart repo may help you, they appear to have that version: https://chartcenter.io/datawire/ambassador?version=2.1.0

**Comment by schollii** [comment]
I did find it thanks!
