### ISSUE TITLE
Helm Chart not correctly create all AES resources when using custom repository

### ISSUE THREAD

**Issue by dw-support** [datawire/ambassador-chart#19]
The chart checks that the AES is being installed before configuring certain options (like the `REDIS_URL` environment variable,

Unfortunately, this check assumed people were only installing the AES from the `dataewire/aes` repository which is an incorrect assumption to make.

There should instead be a simple flag in the chart that, if `true` installs all of the AES stuff.

`.Values.enableAES` should suffice and will be set to `true` by default gz#91

**Comment by nbkrause** [comment]
This is actually much larger than just redis. It is failing to create all AES resources

**Comment by nbkrause** [comment]
Resolved with #20
