### ISSUE TITLE
roles lacks authorities when installing with singeNamespace=true

### ISSUE THREAD

**Issue by chinltong** [datawire/ambassador-chart#26]
installing Ambassador EdgeStack with this command:

`helm upgrade --install ambassador-ingress-controller datawire/ambassador --set scope.singleNamespace=true --namespace ingress-controller`

ambassador pods crashes, see attached log. 
**lines:3,5,9,11,&97**

[errorlog.txt](https://github.com/datawire/ambassador-chart/files/4216157/errorlog.txt)

Ambassador pods can run once I added the clusterrole and clusterrolebinding for `ambassador-ingress-controller` by following the logic for `scope.singleNamespace` is false.

[edge-stack-roles-ingress-controller_yaml.txt](https://github.com/datawire/ambassador-chart/files/4216172/edge-stack-roles-ingress-controller_yaml.txt)

**Comment by acookin** [comment]
This looks to be resolved in newer versions of ambassador (the issue doesn't come up in the latest release 6.5.21)
