### ISSUE TITLE
Service annotation data type is wrong

### ISSUE THREAD

**Issue by Aeysol** [datawire/ambassador-chart#28]
Defining annotations inside `service.annotations` leads to warnings during deployment and no annotations are set for the service.

The warning Helm reports is:
```
coalesce.go:199: warning: destination for annotations is a table. Ignoring non-table value <nil>
```
This could easily be fixed by setting the `annotations` key in the charts `values.yaml` explicitely to an associative array:
```
annotations:
  {}
```

**Comment by acookin** [comment]
looks like this was fixed in https://github.com/datawire/ambassador-chart/pull/48
