### ISSUE TITLE
Generate AES manifests as part of the CI release process

### ISSUE THREAD

**Issue by inercia** [datawire/ambassador-chart#60]
The Helm chart is not in sync with the manifests provided (at https://www.getambassador.io/yaml/aes.yaml) for installing AES. For example, the label scheme in Helm is inconsistent with the YAML installs. In addition, the Helm chart does not have consistent annotations (e.g., the Consul, Istio sidecar injection are in YAML only).

We need to make the Helm chart consistent with the YAML, and develop a way for this to be consistent going forward.

We would like to use the Helm Chart as the only source of truth and generate the manifests as part of the CI process. That means that we could:

- create a new `./ci/push_manifests.sh` script for generating the YAML files as part of [our deployment process](https://github.com/datawire/ambassador-chart/blob/master/.travis.yml#L35-L41).
- this script would basically run a `helm template` with some `values.yaml`.
  - We use our current [values.yaml](https://github.com/datawire/ambassador-chart/blob/master/values.yaml) as the base values, but we can override values with some target-specific `values.yaml` file.
    - a specific `deploymentTool` would be set.
- we should then publish the manifests somewhere. That could be in AWS (as we already do for the Helm chart) or somewhere else, as long as we can have a _permalink_ to those files.
- all the references to the old `aes.yaml`/`aes-crds.yaml` in the `/docs` will be replaced by links to this new permalink.

# Acceptance criteria

- [x] We have a script for generating the manifest(s).
- [ ] We have generated all the manifests we currently have with the combination of 1) the scripts 2) some specific `values.yaml`.
- [ ] Update the documentation about the release process in Notion

**Comment by inercia** [comment]
Being implemented in [this PR](https://github.com/datawire/ambassador-chart/pull/70) (see [diff](https://github.com/datawire/ambassador-chart/compare/inercia/gen_manifests)).

**Comment by inercia** [comment]
Differences being tracked in https://docs.google.com/document/d/1kVQpO87lvEvdu7Me2_GpJO02qNYWFCj8kl4tlLNE84c/edit

**Comment by acookin** [comment]
This work is being tracked by datawire/apro#1280. Closing this issue in the interest of issue cleanup since we've moved the contents of this repo [here](https://github.com/datawire/ambassador/tree/master/charts/ambassador)
