### ISSUE TITLE
Complete Chart Repatriation

### ISSUE THREAD

**Issue by nbkrause** [datawire/ambassador-chart#9]
We have successfully moved the Ambassador chart under the Datawire organization. 

Steps to finish repatriation of the chart:

- [x] Update our index.yaml with all Chart versions that were published on [helm/charts](https://github.com/helm/charts)

- [x] Update the README of [helm/charts/stable/ambassador](https://github.com/helm/charts/tree/master/stable/ambassador) to indicate the chart has been deprecated

- [ ] Ensure we are following all [best practices](https://helm.sh/docs/topics/chart_best_practices/)

- [ ] Update Helm Hub to point to this chart

**Comment by acookin** [comment]
closing because helm hub seems to be pointing at the right place, and the chart is now moving to ambassador.git.
